# Generated by Django 4.2.4 on 2023-09-05 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomTag',
        ),
    ]
